inherit_from:
  - .rubocop_airbnb.yml
AllCops:
  Exclude:
    - 'app/helpers/*'
    - 'bin/*'
    - 'db/**/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
